//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.Xe = new HashSet<Xe>();
        }
    
        public int MaHoaDon { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public Nullable<double> ThanhToan { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual ICollection<Xe> Xe { get; set; }
    }
}
