//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiXe
    {
        public LoaiXe()
        {
            this.Xe = new HashSet<Xe>();
        }
    
        public int MaLoaiXe { get; set; }
        public string TenLoaiXe { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<Xe> Xe { get; set; }
    }
}
