//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLy
    {
        public int MaQuanLy { get; set; }
        public string TenQuanLy { get; set; }
        public string PassQuanLy { get; set; }
    }
}
